# 头部菜单，title: link
menu:
  Whoami: /whoami.html
  Github: https://github.com/CodersGit
  Twitter: https://twitter.com/PolarWooolf
  VK: https://vk.com/itoxicdev

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3:

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '0ce8ea29d4d8f21d02ed'
    # 应用秘钥
    clientSecret: 'dc2bae896869e1c0b63a7851d2a147d69aa37f4c'
    # issue仓库名
    repo: 'iToxicDev'
    # Github名
    owner: 'CodersGit'
    # Github名
    admin: ['CodersGit']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: PolarWolf STRELOK2022 BlogOfCoder PolarWooolf

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
