on:
  push:
    branches:
    - master
name: Deploy to GH Pages
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
      - name: Do all
        run: |
          npm ci
          npm install hexo-cli -g
          hexo clean
          hexo generate
          hexo deploy
